name: pytest

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - "main"


jobs:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v4
    - uses: astral-sh/setup-uv@v5
    - run: uv python install
    - run: uv sync
    - run: pytest -vv