name: pytest

on:
  push:
    branches: "main"
  pull_request:
    branches: "*"


jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
      - run: uv python install
      - run: uv sync
      - run: pytest -vv